# permissions for end users to edit imoocpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imoocpod-editor-role
rules:
- apiGroups:
  - k8s.imooc.com.cmss
  resources:
  - imoocpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.imooc.com.cmss
  resources:
  - imoocpods/status
  verbs:
  - get
